import type { EditableIsland } from "@superobjective/editable-core";

export type SuperobjectiveVitePluginOptions = {
  islands: EditableIsland[];
  outFile?: string;
  alchemyOutFile?: string;
  workerEntrypoint?: string;
  orchestratorClassName?: string;
  orchestratorBinding?: string;
  loaderBinding?: string;
  aiBinding?: string;
  aiGatewayId?: string;
  editModel?: string;
};

export type SuperobjectiveManifest = {
  version: 1;
  workerEntrypoint?: string;
  orchestrator: {
    className: string;
    binding: string;
  };
  dynamicWorkerLoader: {
    binding: string;
  };
  ai: {
    binding: string;
    gatewayId: string;
    editModel: string;
  };
  islands: Array<{
    id: string;
    title?: string;
    rendering: EditableIsland["rendering"];
    cache: EditableIsland["cache"];
    tools: EditableIsland["manifest"]["tools"];
  }>;
};

export function superobjective(
  options: SuperobjectiveVitePluginOptions,
): {
  name: string;
  configResolved(config: { root: string }): void;
  buildStart(): Promise<void>;
} {
  let root = ".";
  const outFile = options.outFile ?? ".superobjective/manifest.json";
  const alchemyOutFile =
    options.alchemyOutFile ?? ".superobjective/alchemy.generated.ts";

  return {
    name: "default-islands",
    configResolved(config) {
      root = config.root;
    },
    async buildStart() {
      const { mkdir, writeFile } = await import("node:fs/promises");
      const { dirname, resolve } = await import("node:path");
      const manifest = createSuperobjectiveManifest(options);
      const manifestPath = resolve(root, outFile);
      const alchemyPath = resolve(root, alchemyOutFile);

      await mkdir(dirname(manifestPath), { recursive: true });
      await mkdir(dirname(alchemyPath), { recursive: true });
      await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
      await writeFile(alchemyPath, createAlchemyGeneratedModule(manifest));
    },
  };
}

export function createSuperobjectiveManifest(
  options: SuperobjectiveVitePluginOptions,
): SuperobjectiveManifest {
  return {
    version: 1,
    workerEntrypoint: options.workerEntrypoint,
    orchestrator: {
      className: options.orchestratorClassName ?? "SuperobjectiveOrchestrator",
      binding: options.orchestratorBinding ?? "SO_ORCHESTRATOR",
    },
    dynamicWorkerLoader: {
      binding: options.loaderBinding ?? "SO_LOADER",
    },
    ai: {
      binding: options.aiBinding ?? "AI",
      gatewayId: options.aiGatewayId ?? "default",
      editModel: options.editModel ?? "@cf/qwen/qwen2.5-coder-32b-instruct",
    },
    islands: options.islands.map((island) => ({
      id: island.id,
      title: island.title,
      rendering: island.rendering,
      cache: island.cache,
      tools: island.manifest.tools,
    })),
  };
}

function createAlchemyGeneratedModule(manifest: SuperobjectiveManifest): string {
  return `// Generated by superobjective() Vite plugin.
export const superobjectiveManifest = ${JSON.stringify(manifest, null, 2)} as const;
`;
}
