// Generated by superobjective() Vite plugin. Do not edit.
// @ts-nocheck
import { createFileRoute } from "@tanstack/react-router";
import { handleSuperobjectiveRequest } from "../../.superobjective/superobjective.server";

export const Route = createFileRoute("/_so/$")({
  server: {
    handlers: {
      GET: ({ request }) => handleSuperobjectiveRequest(request),
      POST: ({ request }) => handleSuperobjectiveRequest(request),
    },
  },
});
